Vagrant.configure("2") do |config|

    (0..5).each do |i|

        config.vm.define "host#{i}" do |host|

			# 设置虚拟机的Box
			#host.vm.box = "bento/centos-6.7"
			#host.vm.box = "bento/centos-7.2"
			host.vm.box = "centos7"

			# 设置虚拟机的主机名
			host.vm.hostname="host#{i}"

			# 设置虚拟机的IP
			#host.vm.network "private_network", ip: "192.168.1.10#{i}"
			host.vm.box_check_update = false

			host.vm.network "public_network", ip: "192.168.1.6#{i}", bridge: "en1: Wi-Fi (AirPort)"


			# 共享目录
			#host.vm.synced_folder "D:/Work/PyCharm/", "/vagrant"
			#host.vm.synced_folder "G:/CentOS Downloads", "/vagrant/downloads"
			host.vm.synced_folder ".", "/vagrant"

			# VirtaulBox相关配置
			host.vm.provider "virtualbox" do |v|

				# 设置虚拟机的名称
				v.name = "host#{i}"

				# 设置虚拟机的内存大小  
				v.memory = 8192

				# 设置虚拟机的CPU个数
				v.cpus = 4
			end
  
			# 使用shell脚本进行软件安装和配置
			host.vm.provision "shell", inline: <<-SHELL
				# 设置阿里云源
				curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
				# 更新 yum
				# yum -y update
			SHELL
        end
    end
end
