Vagrant.configure("2") do |config|

    (0..1).each do |i|

        config.vm.define "host#{i}" do |host|

			# 设置虚拟机的Box
			#host.vm.box = "bento/centos-6.7"
			#host.vm.box = "bento/centos-7.2"
			host.vm.box = "CentOS-7-x86_64-Vagrant-1902_01.VirtualBox.box"

			# 设置虚拟机的主机名
			host.vm.hostname="host#{i}"

			# 设置虚拟机的IP
			#host.vm.network "private_network", ip: "192.168.1.10#{i}"
			host.vm.box_check_update = false
			# http://99.12.206.210
			host.vm.network "public_network", ip: "99.12.206.21#{i}"
			# default router
			host.vm.provision "shell",
				run: "always",
				inline: "route add default gw 99.12.206.253"
			# manual ip
			host.vm.provision "shell",
				run: "always",
				inline: "ifconfig eth1 netmask 255.255.255.0 up"

			# 共享目录
			#host.vm.synced_folder "D:/Work/PyCharm/", "/vagrant"
			#host.vm.synced_folder "G:/CentOS Downloads", "/vagrant/downloads"
			host.vm.synced_folder ".", "/vagrant",disabled:true //禁用vagrant的默认共享目录

			# VirtaulBox相关配置
			host.vm.provider "virtualbox" do |v|

				# 设置虚拟机的名称
				v.name = "host#{i}"

				# 设置虚拟机的内存大小  
				v.memory = 256

				# 设置虚拟机的CPU个数
				v.cpus = 1
			end
  
			# 使用shell脚本进行软件安装和配置
			host.vm.provision "shell", inline: <<-SHELL
				# 设置阿里云源
				curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
				#curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.163.com/.help/CentOS7-Base-163.repo
				# 更新 yum
				# yum -y update
				yum -y remove openssh*
				yum -y install openssh-server net-tools lsof
				sudo systemctl restart sshd		
			SHELL
        end
    end
end
