mysql_repl_user: repl
mysql_repl_password: Admin001
gtid: False
mysql_port: 3306
mysql_password: Admin001
#mysql_innodb_buffer_pool_size: 4G

#ssh root passwd
ssh_password: "vagrant"

if_name: "eth1:1"
app_name: "app1"
mha_vip: 192.168.1.120/24
